apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  template:
    spec:
      containers:
      - name: mariadb-init
        image: mariadb:10.4
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-password
              key: password
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-user-creds
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-user-creds
              key: password
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Never
      volumes:
      - name: init-script
        configMap:
          name: db-init-script
          items:
          - key: db-load-script.sql
            path: db-load-script.sql