apiVersion: v1
kind: ConfigMap
metadata: 
  name: mariadb-config
data:
  my.cnf: |
    [mysqld]
    port = 3306
    basedir = /var/lib/mysql
    datadir = /var/lib/mysql/data
    socket = /var/lib/mysql/mysql.sock
    bind-address = 0.0.0.0