apiVersion: v1
kind: Service
metadata:
  labels:
    app: ecomdb
  name: mariadb-deployment
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 80
  selector:
    app: mariadb-deployment
  type: NodePort