
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  db_host: <base64 encoded value>
  db_user: <base64 encoded value>
  db_password: <base64 encoded value>
  db_name: <base64 encoded value>